version: "3"

services:

  nginx:
    image: nginx:latest
    restart: unless-stopped
    # Possible options: no,on-failure[:max-retries],always,unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${PHP_SOURCE}:/var/www/html
      - ./nginx_server.conf:/etc/nginx/conf.d/default.conf
  
  php-fpm:
    image: php:fpm
    restart: unless-stopped
    build:
      context: . 
      dockerfile: php_Dockerfile
    volumes:
      - ${PHP_SOURCE}:/var/www/html
      - ./php_ini:/usr/local/etc/php/custom.d
      - ./nginx_logs:/var/log/nginx
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    depends_on:
      - nginx

  postgresql:
    image: postgres:latest
    restart: unless-stopped
    build:
      context: . 
      dockerfile: postgresql_Dockerfile
    volumes:
      - ./sql_data:/var/lib/postgresql/data
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DBNAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: ${DB_INITDB_ARGS}
    depends_on:
      - php-fpm
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: 'yep'
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    depends_on:
      - postgresql
